#include <TinyGPS++.h>
#include <HardwareSerial.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Preferences.h>
#include <WiFi.h>
#include <ESP_Mail_Client.h>
#include "config.h"   // <-- WiFi + email credentials live here (see config.h.example)

#define GPS_RX 16
#define GPS_TX 17
#define BTN_PIN 4
#define BUZZER_PIN 5
#define SCR_W 128
#define SCR_H 64

Adafruit_SSD1306 display(SCR_W, SCR_H, &Wire, -1);
TinyGPSPlus gps;
HardwareSerial gpsSerial(1);
Preferences prefs;
SMTPSession smtp;

double curLat = 0, curLng = 0, lastLat = 0, lastLng = 0;
bool gpsOk = false;

int pressCount = 0;
unsigned long lastPress = 0, lastDebounce = 0, lastWifiTry = 0;
bool btnState = HIGH, lastBtnState = HIGH;

const unsigned long DEBOUNCE_MS = 50, PRESS_WINDOW_MS = 1000, WIFI_RETRY_MS = 10000;

void drawCenter(const char* l1, const char* l2, const char* l3 = "") {
  display.clearDisplay();
  const char* lines[3] = { l1, l2, l3 };
  int n = 0;
  for (auto l : lines) if (l && l[0]) n++;
  int y = (SCR_H - n * 10) / 2, row = 0;
  int16_t x1, y1; uint16_t w, h;
  for (auto l : lines) {
    if (!l || !l[0]) continue;
    display.getTextBounds(l, 0, 0, &x1, &y1, &w, &h);
    display.setCursor((SCR_W - w) / 2, y + row * 10);
    display.print(l);
    row++;
  }
  display.display();
}

double activeLat() { return gpsOk ? curLat : lastLat; }
double activeLng() { return gpsOk ? curLng : lastLng; }

void readGPS() {
  while (gpsSerial.available()) gps.encode(gpsSerial.read());
  gpsOk = gps.location.isValid();
  if (gpsOk) {
    curLat = gps.location.lat();
    curLng = gps.location.lng();
    lastLat = curLat; lastLng = curLng;
    prefs.putDouble("lat", lastLat);
    prefs.putDouble("lng", lastLng);
  }
}

bool connectWiFi(unsigned long timeoutMs) {
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  unsigned long start = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - start < timeoutMs) delay(300);
  return WiFi.status() == WL_CONNECTED;
}

void maintainWiFi() {
  if (WiFi.status() == WL_CONNECTED || millis() - lastWifiTry < WIFI_RETRY_MS) return;
  lastWifiTry = millis();
  WiFi.disconnect();
  WiFi.begin(WIFI_SSID, WIFI_PASS);
}

String emailBody(bool loud) {
  String b; b.reserve(700);
  b += "Dear Emergency Contact,\n\nThis is an automated emergency alert generated by the SHUROKKHA Personal Safety System.\n\n";
  b += loud ? "A Loud SOS has been activated. The user may be in immediate danger and requires urgent assistance.\n\n"
            : "A Silent SOS has been activated by the user. The user may be in a situation where they cannot communicate openly and may require immediate assistance.\n\n";
  b += "Current Location:\nhttps://maps.google.com/?q=" + String(activeLat(), 6) + "," + String(activeLng(), 6) + "\n\n";
  b += loud ? "Please respond immediately or contact the nearest emergency service if necessary.\n\n"
            : "Please check on the user's safety as soon as possible.\n\n";
  b += "This message was automatically generated by the SHUROKKHA Safety System.\n\nRegards,\n\nSHUROKKHA\n";
  b += "----------------------------------------\n\nSHUROKKHA\nESP32-Based Personal Safety System\n\nThis is an automatically generated email.\nPlease do not reply.";
  return b;
}

bool sendEmailAlert(bool loud) {
  if (WiFi.status() != WL_CONNECTED && !connectWiFi(8000)) return false;

  Session_Config config;
  config.server.host_name = SMTP_HOST;
  config.server.port = SMTP_PORT;
  config.login.email = MAIL_USER;
  config.login.password = MAIL_PASS;
  config.login.user_domain = "";

  SMTP_Message msg;
  msg.sender.name = "SHUROKKHA";
  msg.sender.email = MAIL_USER;
  msg.subject = loud ? "\xF0\x9F\x94\xB4 SHUROKKHA \xE2\x80\x93 Urgent Emergency Alert"
                     : "\xF0\x9F\x9F\xA1 SHUROKKHA \xE2\x80\x93 Silent Emergency Alert";
  msg.addRecipient("Emergency Contact", MAIL_TO);
  String body = emailBody(loud);
  msg.text.content = body.c_str();
  msg.text.charSet = "utf-8";
  msg.text.transfer_encoding = Content_Transfer_Encoding::enc_7bit;

  smtp.debug(0);
  if (!smtp.connect(&config)) return false;
  bool ok = MailClient.sendMail(&smtp, &msg);
  smtp.closeSession();
  return ok;
}

void sos(bool loud) {
  drawCenter("SHUROKKHA", loud ? "LOUD SOS" : "Silent SOS", "Sending...");
  if (loud) digitalWrite(BUZZER_PIN, HIGH);

  bool ok = sendEmailAlert(loud);

  drawCenter("SHUROKKHA", ok ? "EMAIL SENT" : "EMAIL FAILED");
  delay(2000);
  digitalWrite(BUZZER_PIN, LOW);
  drawCenter("SHUROKKHA", "Ready");
}

void readButton() {
  bool reading = digitalRead(BTN_PIN);
  if (reading != lastBtnState) lastDebounce = millis();

  if (millis() - lastDebounce > DEBOUNCE_MS && reading != btnState) {
    btnState = reading;
    if (btnState == LOW) { pressCount++; lastPress = millis(); }
  }
  lastBtnState = reading;

  if (pressCount > 0 && millis() - lastPress > PRESS_WINDOW_MS) {
    if (pressCount == 2) sos(false);
    else if (pressCount == 3) sos(true);
    pressCount = 0;
  }
}

void setup() {
  Serial.begin(115200);
  pinMode(BTN_PIN, INPUT_PULLUP);
  pinMode(BUZZER_PIN, OUTPUT);
  digitalWrite(BUZZER_PIN, LOW);

  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
  display.setTextColor(SSD1306_WHITE);
  display.setTextSize(1);
  drawCenter("SHUROKKHA", "Initializing...");

  prefs.begin("gps", false);
  lastLat = prefs.getDouble("lat", 0.0);
  lastLng = prefs.getDouble("lng", 0.0);

  gpsSerial.begin(9600, SERIAL_8N1, GPS_RX, GPS_TX);

  drawCenter("SHUROKKHA", "Connecting WiFi...");
  connectWiFi(8000);

  drawCenter("SHUROKKHA", "Ready");
}

void loop() {
  readGPS();
  readButton();
  maintainWiFi();
}
